### ISSUE TITLE
Setup Windows builds in Azure Pipelines

### ISSUE THREAD

**Issue by jfro** [jfro/dnssd-rs#8]
This requires figuring out how to install the Bonjour SDK automatically, which I've only seen the runtime version available on things like Chocolatey.

Bonjour SDK is a login gated download from apple currently.

**Comment by hrueger** [comment]
Any updates on this? I would like to do the same thing...

**Comment by melMass** [comment]
> Bonjour SDK is a login gated download from apple currently.

I don't think they are: https://download.developer.apple.com/Developer_Tools/bonjour_sdk_for_windows_v3.0/bonjoursdksetup.exe

**Comment by jfro** [comment]
we'd probably also switch to GH as we've done that internally, also we could get CI going for the non-bonjour windows APIs as that doesn't require installing anything

**Comment by jfro** [comment]
> > Bonjour SDK is a login gated download from apple currently.
> 
> I don't think they are: https://download.developer.apple.com/Developer_Tools/bonjour_sdk_for_windows_v3.0/bonjoursdksetup.exe

this link doesn't seem to work for me at least, other thought is hosting the download ourselves so CI can easily get it.
